vim.cmd "colorscheme ferrum"
vim.cmd "set shell=fish"
vim.cmd "set timeoutlen=1000"

require "adam.options"
require "adam.keymaps"
require "adam.plugins"
require "adam.toggleterm"
require "adam.cmp"
require "adam.lsp"
require "adam.telescope"
require "adam.treesitter"
require "adam.autopairs"
require "adam.gitsigns"
